import { RiFacebookBoxFill, RiInstagramFill, RiMailAiFill, RiMapPin2Fill, RiPhoneFill, RiPinterestFill, RiTwitterFill, RiYoutubeFill } from "@remixicon/react";

export const SiteConfig = {
  authorName: "Md Bappi",
  brandName: "Rescue Car Battery Dubai",
  url: "https://www.rescuecarbatterydubai.com",
  logo: "", 
  ogImage: "",
  email: "rescuecarbattery@gmail.com",
  foundedYear: "2017",
  emailLink: "mailto:onfixcarrepair@gmail.com",
  description:"Rescue Car Battery Dubai provides 24/7 fast, professional and reliable mobile battery replacement service at your doorstep across Dubai.",
  displayNumber: "+054 000 0000",
  numberCallLink: "tel:+9710000000",
  whatsappCallLink: "https://wa.me/97100000000",
  location: "60 Street, Nadd Hessa - Industrial Area, Dubai, UAE",
  streetAddress: "60 Street, Nadd Hessa",
  addressLocality: "Dubai",
  addressRegion: "Dubai",
  addressCountry: "AE",
  postalCode: "00000",
  mapsLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28884.938197365485!2d55.25122003473435!3d25.18239777407417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f682def25f457%3A0x3dd4c4097970950e!2sBusiness%20Bay%20-%20Dubai%20-%20United%20Arab%20Emirates!5e0!3m2!1sen!2sbd!4v1788196351232!5m2!1sen!2sbd",

  GMB: {
    name: "OnFix Car Repair Mechanic Dubai",
    placeId: "",
    cid: "",
    category: "Auto Battery Shop",
    mapsLink: "https://maps.app.goo.gl/4uy48BNYQQSsC7MC9",
    latitude: "",
    longitude: "",
  },

serviceAreas :[
  { name: "Al Karama" },
  { name: "Al Mankhool" },
  { name: "Damac Hills" },
  { name: "Business Bay" },
  { name: "Downtown Dubai" },
  { name: "Al Satwa" },
  { name: "DIFC" },
  { name: "Dubai Silicon Oasis" },
  { name: "Deira" },
  { name: "Dubai Marina" },
  { name: "Al Rigga" },
  { name: "Al Raffa" },
  { name: "Dubai Creek" },
  { name: "Al Jaddaf" },
  { name: "Zabeel First" },
  { name: "Dubai Festival City" },
  { name: "City Walk" },
  { name: "Jumeirah" },
  { name: "Al Quoz" },
  { name: "Al Hudaiba" },
  { name: "Al Jafiliya" }
],

  operatingHours: [
    { day: "Saturday", hours: "24 Hours" },
    { day: "Sunday", hours: "24 Hours" },
    { day: "Monday", hours: "24 Hours" },
    { day: "Tuesday", hours: "24 Hours" },
    { day: "Wednesday", hours: "24 Hours" },
    { day: "Thursday", hours: "24 Hours" },
    { day: "Friday", hours: "24 Hours" },
  ],

  city: "Dubai",
  country: "UAE",

  navItems: [
    { name: "Home", href: "/" },
    { name: "Services", href: "/services" },
    { name: "Areas We Serve", href: "/area-we-serve" },
    { name: "About", href: "/about" },
    { name: "Contact", href: "/contact" },
    { name: "Blog", href: "/blog" },
  ],

  footerhrefs: [
    { title: "About Us", href: "/about" },
    { title: "Contact", href: "/contact" },
    { title: "Services", href: "/services" },
    { title: "Privacy Policy", href: "/privacy" },
    { title: "Terms of Service", href: "/terms" },
    { title: "Sitemap", href: "/sitemap.xml" },
  ],

  socialLinks: [
    { name: "Facebook", icon: RiFacebookBoxFill, href: "" },
    { name: "Instagram", icon: RiInstagramFill, href: "" },
    { name: "Pinterest", icon: RiPinterestFill, href: "" },
    { name: "X", icon: RiTwitterFill, href: "" },
    { name: "YouTube", icon: RiYoutubeFill, href: "" },
  ],

  contactLinks: [
    { name: "Map", icon: RiMapPin2Fill, href: ""},
    { name: "Phone", icon: RiPhoneFill, href: "tel: "},
    { name: "Email", icon: RiMailAiFill, href: "mailto:" },
  ],
};

export const {
  contactLinks,
  socialLinks,
  footerhrefs,
  navItems,
  serviceAreas,
  location,
  streetAddress,
  addressLocality,
  addressRegion,
  addressCountry,
  postalCode,
  mapsLink,
  embedMap,
  numberCallLink,
  whatsappCallLink,
  operatingHours,
  displayNumber,
  description,
  email,
  url,
  brandName,
  authorName,
  city,
  country,
  GMB,
} = SiteConfig;

